#!/bin/bash

echo "Installing ohmyzsh.."
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo "Installing Homebrew..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

echo "Installing Homebrew dependencies from Brewfile..."
brew bundle

echo "Installing Rbenv default gems..."
mkdir -p "$(rbenv root)/plugins"
git clone https://github.com/rbenv/rbenv-default-gems.git "$(rbenv root)/plugins/rbenv-default-gems"

ln -s -f "$HOME/.dotfiles/ruby/irbrc" ~/.irbrc
ln -s -f "$HOME/.dotfiles/ruby/default-gems" "$(rbenv root)/default-gems"

echo "source $HOME/.zshrc" >> .zshrc
