#!/bin/bash

echo "Installing ohmyzsh.."
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo "Installing Homebrew..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

echo "Installing Homebrew dependencies from Brewfile..."
brew bundle install --verbose --no-lock

echo "Installing Rbenv default gems..."
mkdir -p "$(rbenv root)/plugins"
git clone https://github.com/rbenv/rbenv-default-gems.git "$(rbenv root)/plugins/rbenv-default-gems"

ln -s -f "$HOME/.dotfiles/ruby/irbrc" ~/.irbrc
ln -s -f "$HOME/.dotfiles/ruby/default-gems" "$(rbenv root)/default-gems"

echo "Hiding desktop icons..."
defaults write com.apple.finder CreateDesktop false
killall Finder

echo "Setting keymappings..."
ln -s -f "$HOME/.dotfiles/karabiner" "$HOME/.config"

echo "Installing Dalmatian tooks"
git clone git@github.com:dxw/dalmatian-tools.git "$HOME/Documents/dalmatian-tools"
(cd "$HOME/Documents/dalmatian-tools" || exit; brew bundle install)

echo "source $HOME/.dotfiles/.zshrc" >> "$HOME/.zshrc"
