#!/bin/bash
set -e

curl -fsSL --retry 3 --insecure "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.darwin.x86_64.tar.xz" | sudo tar xz --no-same-owner --strip-components=1 -C /usr/local/bin/ shellcheck*/shellcheck

files=$(grep -rl '^#!/.*bash' .)

for file in $files
do
  shellcheck "$file"
done
